# swagger service for Azure Virtual Machines
swagger: '2.0'
info:
  version: '0.0.3'
  title: 'Azure REST Service Using Swagger'
  description: 'Rest Service that allows to create and manage VMs on Azure'
  contact:
    name: 'Cloudmesh Azure REST service'
  license:
    name: 'Apache'

host: 'localhost:8080'
basePath: '/cloudmesh/azure'

schemes:
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'


paths:
  '/resourcegroup/{id}':
    get:
      description: "Returns details of resource group with given name"
      operationId: getResourceGroupById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the resource group'
          required: true
          type: string
      responses:
        '200':
          description: 'Details of resource group of given name'
          schema:
            $ref: '#/definitions/Resourcegroup'

  '/resourcegroup/create/{id}':
    get:
      description: "Creates new resource group with given name"
      operationId: createResourceGroupById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the resource group'
          required: true
          type: string
      responses:
        '200':
          description: 'Result of resource group creation'
          schema:
            type: string

  '/vm/{id}':
    get:
      description: "Returns details of virtual machine with given name"
      operationId: getVirtualMachineById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the virtual machine'
          required: true
          type: string
      responses:
        '200':
          description: 'Details of virtual machine of given name'
          schema:
            $ref: '#/definitions/VM'

  '/vm/create/{id}':
    get:
      description: "Creates new vitual machine with given name"
      operationId: createVirtualMachineById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the virtual machine'
          required: true
          type: string
      responses:
        '200':
          description: 'Result of virtual machine creation'
          schema:
            type: string

  '/vm/start/{id}':
    get:
      description: "Start vitual machine with given name"
      operationId: startVirtualMachineById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the virtual machine'
          required: true
          type: string
      responses:
        '200':
          description: 'Result of starting virtual machine'
          schema:
            type: string

  '/vm/stop/{id}':
    get:
      description: "Stop vitual machine with given name"
      operationId: stopVirtualMachineById
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: 'name of the virtual machine'
          required: true
          type: string
      responses:
        '200':
          description: 'Result of stopping virtual machine'
          schema:
            type: string

definitions:
  Resourcegroup:
    type: "object"
    properties:
      name:
        type: "string"
      tags:
        type: "string"
      id:
        type: "string"
      managed_by:
        type: "string"
      location:
        type: "string"
      properties:
        type: "object"
        properties:
          provisioningState:
            type: "string"

  VM:
    type: "object"
    properties:
      identity:
        type: "string"
      os_profile:
        type: "object"
        properties:
          computer_name:
            type: "string"
          admin_username:
            type: "string"
          admin_password:
            type: "string"
      storage_profile:
        type: "object"
        properties:
          image_ref:
            type: "object"
            properties:
              publisher:
                type: "string"
              offer:
                type: "string"
              sku:
                type: "string"
              version:
                type: "string"
      name:
        type: "string"
      tags:
        type: "string"
      vm_id:
        type: "string"
      hardware_profile:
        type: "object"
        properties:
          vm_size:
            type: "string"
      provisioning_state:
        type: "string"
      network_profile:
        type: "object"
        properties:
          network_interface:
            type: "string"
      type:
        type: "string"
      id:
        type: "string"
      location:
        type: "string"









