# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VMHardwareProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vm_size=None):  # noqa: E501
        """VMHardwareProfile - a model defined in Swagger

        :param vm_size: The vm_size of this VMHardwareProfile.  # noqa: E501
        :type vm_size: str
        """
        self.swagger_types = {
            'vm_size': str
        }

        self.attribute_map = {
            'vm_size': 'vm_size'
        }

        self._vm_size = vm_size

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VM_hardware_profile of this VMHardwareProfile.  # noqa: E501
        :rtype: VMHardwareProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vm_size(self):
        """Gets the vm_size of this VMHardwareProfile.


        :return: The vm_size of this VMHardwareProfile.
        :rtype: str
        """
        return self._vm_size

    @vm_size.setter
    def vm_size(self, vm_size):
        """Sets the vm_size of this VMHardwareProfile.


        :param vm_size: The vm_size of this VMHardwareProfile.
        :type vm_size: str
        """

        self._vm_size = vm_size
