# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VMOsProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, computer_name=None, admin_username=None, admin_password=None):  # noqa: E501
        """VMOsProfile - a model defined in Swagger

        :param computer_name: The computer_name of this VMOsProfile.  # noqa: E501
        :type computer_name: str
        :param admin_username: The admin_username of this VMOsProfile.  # noqa: E501
        :type admin_username: str
        :param admin_password: The admin_password of this VMOsProfile.  # noqa: E501
        :type admin_password: str
        """
        self.swagger_types = {
            'computer_name': str,
            'admin_username': str,
            'admin_password': str
        }

        self.attribute_map = {
            'computer_name': 'computer_name',
            'admin_username': 'admin_username',
            'admin_password': 'admin_password'
        }

        self._computer_name = computer_name
        self._admin_username = admin_username
        self._admin_password = admin_password

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VM_os_profile of this VMOsProfile.  # noqa: E501
        :rtype: VMOsProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def computer_name(self):
        """Gets the computer_name of this VMOsProfile.


        :return: The computer_name of this VMOsProfile.
        :rtype: str
        """
        return self._computer_name

    @computer_name.setter
    def computer_name(self, computer_name):
        """Sets the computer_name of this VMOsProfile.


        :param computer_name: The computer_name of this VMOsProfile.
        :type computer_name: str
        """

        self._computer_name = computer_name

    @property
    def admin_username(self):
        """Gets the admin_username of this VMOsProfile.


        :return: The admin_username of this VMOsProfile.
        :rtype: str
        """
        return self._admin_username

    @admin_username.setter
    def admin_username(self, admin_username):
        """Sets the admin_username of this VMOsProfile.


        :param admin_username: The admin_username of this VMOsProfile.
        :type admin_username: str
        """

        self._admin_username = admin_username

    @property
    def admin_password(self):
        """Gets the admin_password of this VMOsProfile.


        :return: The admin_password of this VMOsProfile.
        :rtype: str
        """
        return self._admin_password

    @admin_password.setter
    def admin_password(self, admin_password):
        """Sets the admin_password of this VMOsProfile.


        :param admin_password: The admin_password of this VMOsProfile.
        :type admin_password: str
        """

        self._admin_password = admin_password
