# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LOF(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id=None, files=None):  # noqa: E501
        """LOF - a model defined in Swagger

        :param id: The id of this LOF.  # noqa: E501
        :type id: str
        :param files: The files of this LOF.  # noqa: E501
        :type files: List[str]
        """
        self.swagger_types = {
            'id': str,
            'files': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'files': 'files'
        }

        self._id = id
        self._files = files

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LOF of this LOF.  # noqa: E501
        :rtype: LOF
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this LOF.


        :return: The id of this LOF.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LOF.


        :param id: The id of this LOF.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def files(self):
        """Gets the files of this LOF.


        :return: The files of this LOF.
        :rtype: List[str]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this LOF.


        :param files: The files of this LOF.
        :type files: List[str]
        """
        if files is None:
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files
