---
swagger: "2.0"
info:
  description: "A simple service to fetch information of variable"
  version: "0.0.1"
  title: "VAriables"
  contact:
    name: "Cloudmesh REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /var:
    get:
      description: "Returns information of variable"
      operationId: "var_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Var info"
          schema:
            $ref: "#/definitions/VAR"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /var/{id}:
    get:
      description: "Returns info of variable by that id"
      operationId: "get_var_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "name of variable"
        required: true
        type: "string"
      responses:
        200:
          description: "Info of variable"
          schema:
            $ref: "#/definitions/VAR"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  VAR:
    type: "object"
    required:
    - "id"
    - "type"
    - "value"
    properties:
      id:
        type: "string"
      value:
        type: "string"
      type:
        type: "string"
    example:
      id: "id"
      type: "type"
      value: "value"
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
