# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResourcegroupProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, provisioning_state=None):  # noqa: E501
        """ResourcegroupProperties - a model defined in Swagger

        :param provisioning_state: The provisioning_state of this ResourcegroupProperties.  # noqa: E501
        :type provisioning_state: str
        """
        self.swagger_types = {
            'provisioning_state': str
        }

        self.attribute_map = {
            'provisioning_state': 'provisioningState'
        }

        self._provisioning_state = provisioning_state

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Resourcegroup_properties of this ResourcegroupProperties.  # noqa: E501
        :rtype: ResourcegroupProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provisioning_state(self):
        """Gets the provisioning_state of this ResourcegroupProperties.


        :return: The provisioning_state of this ResourcegroupProperties.
        :rtype: str
        """
        return self._provisioning_state

    @provisioning_state.setter
    def provisioning_state(self, provisioning_state):
        """Sets the provisioning_state of this ResourcegroupProperties.


        :param provisioning_state: The provisioning_state of this ResourcegroupProperties.
        :type provisioning_state: str
        """

        self._provisioning_state = provisioning_state
