# coding: utf-8

"""
    ListFiles

    A simple service to list all the files under given directory  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lof import LOF  # noqa: E501
from swagger_client.rest import ApiException


class TestLOF(unittest.TestCase):
    """LOF unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLOF(self):
        """Test LOF"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lof.LOF()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
