# coding: utf-8

"""
    ListFiles

    A simple service to list all the files under given directory  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dir_get(self):
        """Test case for dir_get

        """
        pass

    def test_get_file_by_id(self):
        """Test case for get_file_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
