---
swagger: "2.0"
info:
  description: "A simple service to list all the files under given directory"
  version: "0.0.1"
  title: "ListFiles"
  contact:
    name: "Cloudmesh REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /dir:
    get:
      description: "Returns list of files under root directory"
      operationId: "dir_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "CPU info"
          schema:
            $ref: "#/definitions/LOF"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /dir/{id}:
    get:
      description: "Returns list of files under given directory"
      operationId: "get_file_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of directory to fetch"
        required: true
        type: "string"
      responses:
        200:
          description: "The files under given directory"
          schema:
            $ref: "#/definitions/LOF"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  LOF:
    type: "object"
    required:
    - "files"
    - "id"
    properties:
      id:
        type: "string"
      files:
        type: "array"
        items:
          type: "string"
    example:
      files:
      - "files"
      - "files"
      id: "id"
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
