# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VMNetworkProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network_interface=None):  # noqa: E501
        """VMNetworkProfile - a model defined in Swagger

        :param network_interface: The network_interface of this VMNetworkProfile.  # noqa: E501
        :type network_interface: str
        """
        self.swagger_types = {
            'network_interface': str
        }

        self.attribute_map = {
            'network_interface': 'network_interface'
        }

        self._network_interface = network_interface

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VM_network_profile of this VMNetworkProfile.  # noqa: E501
        :rtype: VMNetworkProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_interface(self):
        """Gets the network_interface of this VMNetworkProfile.


        :return: The network_interface of this VMNetworkProfile.
        :rtype: str
        """
        return self._network_interface

    @network_interface.setter
    def network_interface(self, network_interface):
        """Sets the network_interface of this VMNetworkProfile.


        :param network_interface: The network_interface of this VMNetworkProfile.
        :type network_interface: str
        """

        self._network_interface = network_interface
